import { Inter } from 'next/font/google'
import './globals.css'
import StarsCanvas from '@/components/StarBackground'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '< RITIK JAISWAL />',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return ( 
    <html lang="en">
      <body style={{fontFamily: 'Azonix'}} className='{inter.className}'>
        <StarsCanvas />
        {children}
      </body>
    </html>
  )
}
